name: Deploy Astro + Pure to GitHub Pages

on:
  push:
    branches: [main]  # Replace with your branch if different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUN_LINK_PKG: true  # Links Pure locally

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Link Pure & Build Site
        run: |
          bun pure check        # Links local Pure package
          npx astro check           # TypeScript + Astro checks
          npx astro build           # Build static site

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact-path: ./dist

